language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install xml2rfc
# command to run tests, e.g. python setup.py test
script: make upload

env:
 global:
 - GH_REF: github.com/rtcweb-wg/jsep.git
 - secure: secure: "h5W1PE4UCnO87kdYaNer5qp1Gta+PpUBBU79m/eTg1aYEDeq3BPP95MTy2PWO8j2oZab0ujVrwrEwMffTVpQScOe0IXaXLgu8q97qJdk3Nzc5TXNWj9IsarJNNK3Jho3/gpxtz5uNw5q0kdyviEBiC/w+ccpkykiyXX6Zz0f/eg="

