language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install xml2rfc
# command to run tests, e.g. python setup.py test
script: make upload

env:
 global:
 - GH_REF: github.com/rtcweb-wg/jsep.git
 - secure: "W+AD5vSJjEHpFjeBYBF8hcf841/J+Ze5YeIME5p36Y+/inalGcuLJWl8smwCVNyiFXRzlPnrlJyboVgLLhKAG7GUCKExUol+r+fyfeh+j3O2kgadup1eIA6Djo4CC3oSjSeLQUG+IGOqRaat68HTLBDc1OgAdC+nU7DpLq1W50Q="

